version: "2"
services:
    php:
        volumes:
            - "C:\\Users\\davi.aroldi\\Documents\\desenvolvimento\\agronet-php7\\fontes\\:/var/www/html/"
#        depends_on:
#            - db
#        image: php7:v1
        build: .
        privileged: true
        ports:
            - "9001:80"
#        dockerfile: Dockerfile
        restart: always
        links:
            - "db:database"
        container_name: php
        # environment:
        #     COMPOSE_CONVERT_WINDOWS_PATHS: 1
    db:
        image: mysql
        restart: always
        environment:
            # MYSQL_USER:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        container_name: db
        ports:
            - "3306:3306"
        volumes:
            - ".\\db\\:/var/lib/mysql/"